GET http://localhost:3000/

# @ Response
# HTTP/1.1 200 OK
# X-Powered-By: Express
# Access-Control-Allow-Origin: *
# Content-Type: application/json; charset=utf-8
# Content-Length: 19
# ETag: W/"13-Pa/MFmOyCaOzvReId5aJY+w0TX8"
# Date: Wed, 15 Jul 2020 17:11:11 GMT
# Connection: close
#
# {
#   "id": "4a8bf592-e1ba-464c-905e-05a7add1a7c0",
#   "text": "Did you know the first French fries weren't actually cooked in France? They were cooked in Greece.",
#   "created_at": "2020-07-15 17:57:10"
# }
